name: Backend CI

on:
  push:
    branches: ["main", "dev"]
    paths:
      - "backend/**"
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "backend/**"

defaults:
  run:
    working-directory: ./backend/

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: './backend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build --if-present

      - name: Run tests
        run: npm test
